export const centerForm = {
	title: "Book a Tour",
	subtitle: "Fill out the form below and we'll get back to you shortly",
	fields: [
		{
			name: "fullName",
			label: "Full Name:",
			type: "text",
			placeholder: "",
			required: true,
			icon: "user",
		},
		{
			name: "workEmail",
			label: "Work Email:",
			type: "email",
			placeholder: "",
			required: true,
			icon: "email",
		},
		{
			name: "phoneNumber",
			label: "Phone Number:",
			type: "tel",
			placeholder: "",
			required: true,
			icon: "phone",
		},
		{
			name: "companyName",
			label: "Company Name:",
			type: "text",
			placeholder: "",
			required: true,
			icon: "building",
		},
		{
			name: "requirements",
			label: "Select Your Requirements:",
			type: "select",
			placeholder: "Select...",
			required: true,
			options: [],
		},
		{
			name: "city",
			label: "City:",
			type: "select",
			placeholder: "Hyderabad",
			required: true,
			options: [
				"Hyderabad",
				"Bengaluru",
				"Pune",
				"Chennai",
				"Vijayawada",
				"Kolkata",
				"Ahmedabad",
				"Gurugram",
			],
		},
		{
			name: "office",
			label: "Office:",
			type: "select",
			placeholder: "One Gold Mile",
			required: true,
			options: [
				"One Gold Mile",
				"Orbit",
				"Twitza",
				"Sohini Tech Park",
				"Jayabheri Trendset Connect",
				"Divyasree Trinity",
			],
		},
		{
			name: "managerCabin",
			label: "Manager Cabin",
			type: "checkbox",
			required: false,
		},
		{
			name: "conferenceRoom",
			label: "Conference Room",
			type: "checkbox",
			required: false,
		},
		{
			name: "requiredSeats",
			label: "Required Seats:",
			type: "number",
			placeholder: "1",
			required: true,
			min: 1,
			max: 100,
		},
		{
			name: "termsAccepted",
			label: "I accept all of iSprout's terms & conditions",
			type: "checkbox",
			required: true,
		},
	],
	submitButtonText: "Submit",
};
