// Comprehensive City Page Data - Backend Reference
// This file contains all city data consolidated from Description.tsx, CityCenters.tsx, and hero.tsx

export const cityPageData = {
	cities: [
		{
			id: "hyderabad",
			name: "Hyderabad",
			displayName: "Hyderabad",
			aliases: ["hyderabad"],
			heroImage: "Hyderabad.jpg",
			description: {
				title: "Hyderabad's Unique Co-working Spots: Where Ideas Flourish and",
				highlight: "Businesses Bloom",
				text: "Hey there, Hyderabad folks! Looking for a workspace that's as dynamic and exciting as your business ideas? Well, you're in luck! iSprout's flexible managed offices in the city are designed to get your creative juices flowing and your productivity soaring. From solo entrepreneurs cooking up the next big thing to growing startups making waves, these spaces are buzzing with opportunity and collaboration. Whether you choose the sleek vibes of Orbit, My Home Twitza, One Golden Mile, Sohini Tech Park, Jayabheri Trendset Connect, Divyasree Trinity, Purva Summit, Modern Profound, Minaas, Pranava One, and Sreshta Marvel, you'll find state-of-the-art facilities, comfy work areas, and a community of like-minded go-getters. So why settle for a boring office when you can be part of Hyderabad's most inspiring workspace revolution at iSprout?",
			},
			mapCenter: { lat: 17.4435, lng: 78.3772 },
			centers: [
				{
					id: "pranava-one",
					centerKey: "pranava one",
					name: "Pranava One",
					explore: "/centre/pranava-one",
					description: "",
					address:
						"6-5-654, Punjagutta Rd, Raj Bhavan Quarters Colony, Somajiguda, Hyderabad, Telangana 500082",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.419639, lng: 78.457306 },
					nearestCoordinates: [
						{
							name: "metro",
							icon: "train",
							lat: 17.4215,
							lng: 78.456,
							distance: "0.2 km",
						},
					],
					getDirections: "https://maps.app.goo.gl/VaKnctW932Gc1aAe8",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/pranava_Building1.jpg",
						lobby: "../../assets/city/pranava_Lobby2.jpg",
						workspace: "../../assets/city/pranava_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "jayabheri-trendset",
					centerKey: "jayabheri trendset connect",
					name: "Jayabheri Trendset connect",
					explore: "/centre/jayabheri-trendset",
					description: "",
					address:
						"SY No 5 Kondapur village, Madhapur Hyderabad Telangana India 500084",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.4535, lng: 78.370111 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/qD1r9XYgKdFaYZHr9",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/jayabheri_Building1.jpg",
						lobby: "../../assets/city/jayabheri_Lobby2.jpg",
						workspace: "../../assets/city/jayabheri_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "sohini-tech-park",
					centerKey: "sohini tech park",
					name: "Sohini Tech Park",
					explore: "/centre/sohini-tech-park",
					description: "",
					address:
						"8th & 9th Floor, Survey No. 142, Nanakramguda Village, Serilingampally Mandal, RR District, Hyderabad 500032",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.42275, lng: 78.347194 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/tzyneciLAVYLKu8J9",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/sohini_Building1.jpg",
						lobby: "../../assets/city/sohini_Lobby2.jpg",
						workspace: "../../assets/city/sohini_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "my-home-twitza",
					centerKey: "my home twitza",
					name: "My Home Twitza",
					explore: "/centre/my-home-twitza",
					description: "",
					address:
						"Survey No 83/1, APIIC- Hyderabad Knowledge Center, 5th & 6th Floor, Plot No 30/A, Rai Durg, Hyderabad, Telangana 500081",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.433972, lng: 78.374972 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/JWSrpQMhQHr7D2CBA",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/twitza_Building1.jpg",
						lobby: "../../assets/city/twitza_Lobby2.jpg",
						workspace: "../../assets/city/twitza_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "divyasree-trinity",
					centerKey: "divyasree trinity",
					name: "Divyasree Trinity",
					explore: "/centre/divyasree-trinity",
					description: "",
					address:
						"7th & 8th Floor, Plot No. 5, at HITEC City Layout, survey number 64 (part), Madhapur Village, Serilingampally Mandal, R R District, Hyderabad 500081",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.443556, lng: 78.374389 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/b3Sxfi8YWTi54TR86",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/divyasree_Building1.jpg",
						lobby: "../../assets/city/divyasree_Lobby2.jpg",
						workspace: "../../assets/city/divyasree_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "modern-profound",
					centerKey: "modern profound",
					name: "Modern Profound",
					explore: "/centre/modern-profound",
					description: "",
					address:
						"2nd Floor, Survey No. 12, Office No. 201, Kondapur, Hyderabad, Telangana 500032",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.446861, lng: 78.364083 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/HnKWaeCQvpj7bYoE8",
					heroImage: "",
					cityLevelImages: {
						building:
							"../../assets/city/modernprofound_Building1.jpg",
						lobby: "../../assets/city/modernprofound_Lobby2.jpg",
						workspace:
							"../../assets/city/modernprofound_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "orbit",
					centerKey: "orbit",
					name: "ORBIT",
					explore: "/centre/orbit",
					description: "",
					address:
						"Plot No 30/C, Sy No 83/1, Hyderabad Knowledge City Raidurg Panmaktha, Serilingampally Mandal, Hyderabad, Telangana 500019",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.434389, lng: 78.376778 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/Wh2U5irceHDVC9XA8",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/orbit_Building1.jpg",
						lobby: "../../assets/city/orbit_Lobby3.jpg",
						workspace: "../../assets/city/orbit_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "one-golden-mile",
					centerKey: "one golden mile",
					name: "One Golden Mile",
					explore: "/centre/one-golden-mile",
					description: "",
					address:
						"9th Floor, Survey no 113, Golden Mile Rd, Kokapet, Hyderabad, Telangana 500075",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.401028, lng: 78.338389 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/ixmm1eNsN1cvXZ2w5",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/golden_Building1.jpg",
						lobby: "../../assets/city/golden_Lobby2.jpg",
						workspace: "../../assets/city/golden_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "purva-summit",
					centerKey: "purva summit",
					name: "Purva Summit",
					explore: "/centre/purva-summit",
					description: "",
					address:
						"2nd Floor, Survey No 8, Whitefields Road, White Fields, Hitech City, Hyderabad, Telangana 500081",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.419639, lng: 78.457306 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/Sk7LGu31AivnDaSQ7",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/purva_Building1.jpg",
						lobby: "../../assets/city/purva_Lobby2.jpg",
						workspace: "../../assets/city/purva_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "minaas-center",
					centerKey: "minaas center",
					name: "Minaas Center",
					explore: "/centre/minaas-center",
					description: "",
					address: "Minaas Towers, Hyderabad, Telangana",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.442722, lng: 78.368361 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/1rUbi6MujWs2DoHo7",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/minass_Building1.jpg",
						lobby: "../../assets/city/minass_Lobby2.jpg",
						workspace: "../../assets/city/minass_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "sreshta-marvel",
					centerKey: "sreshta marvel",
					name: "Sreshta Marvel",
					explore: "/centre/sreshta-marvel",
					description: "",
					address:
						"2nd floor, Sy.No.136, Kondapur Main Road, P Janardhan Reddy Nagar, Gachibowli, Hyderabad, Telangana 500032",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.237167, lng: 78.428972 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/VRmZmZXFykKPYCWg6",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/sreshta_Building1.jpg",
						lobby: "../../assets/city/sreshta_Lobby3.jpg",
						workspace: "../../assets/city/sreshta_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "sas-tower",
					centerKey: "sas tower",
					name: "SAS Tower",
					explore: "/centre/sas-tower",
					description: "",
					address: "SAS I Tower, Hyderabad, Telangana",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.41925, lng: 78.360111 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/buy6k86xgrx5jChb9",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/sas_Building1.jpg",
						lobby: "../../assets/city/sas_Lobby2.jpg",
						workspace: "../../assets/city/sas_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "bengaluru",
			name: "Bengaluru",
			displayName: "Bengaluru",
			aliases: ["bengaluru", "bangalore"],
			heroImage: "Bangalore.jpg",

			description: {
				title: "Bengaluru's Best Spaces for",
				highlight: "Innovation",
				text: "Bengaluru, India's Silicon Valley, is home to countless startups and tech giants. Our premium coworking spaces are strategically located across key business districts, offering you the perfect environment to collaborate, innovate, and grow. Experience world-class amenities in the heart of India's startup capital.",
			},
			mapCenter: { lat: 13.0827, lng: 80.2707 },
			centers: [
				{
					id: "nr-enclave",
					centerKey: "nr enclave",
					name: "NR Enclave",
					explore: "/centre/nr-enclave",
					description: "",
					address:
						"DivyaSree N R Enclave, 1st Main Rd, KIADB Export Promotion Industrial Area, Whitefield, Bengaluru, Karnataka 560066",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 12.986472, lng: 77.730528 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/ymX6R3suf9hmpkmk7",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/NR_Building1.jpg",
						lobby: "../../assets/city/NR_Lobby2.jpg",
						workspace: "../../assets/city/NR_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "prestige-saleh-ahmed",
					centerKey: "prestige saleh ahmed",
					name: "Prestige Saleh Ahmed",
					explore: "/centre/prestige-saleh-ahmed",
					description: "",
					address:
						"132, Lady Curzon Rd, Tasker Town, Infantry Road, Bangalore, 560001",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 12.980348, lng: 77.603538 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/5RyVHstY57vQWiYQ6",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/prestige_Building1.jpg",
						lobby: "../../assets/city/prestige_Lobby2.jpg",
						workspace: "../../assets/city/prestige_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "shilpitha-tech-park",
					centerKey: "shilpitha tech park",
					name: "Shilpitha Tech Park",
					explore: "/centre/shilpitha-tech-park",
					description: "",
					address:
						"Sakra World Hospital, 55/3 55/4, Shilpitha Tech Park - Maithri Developers, Devarabisanahalli Road Bellandur, Kariyammana Agrahara, Bengaluru Karnataka 560103",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 12.931222, lng: 77.685583 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/MSaxH6RdPrJ1XBTU6",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/shilpitha_Building1.jpg",
						lobby: "../../assets/city/shilpitha_Lobby2.jpg",
						workspace: "../../assets/city/shilpitha_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "chennai",
			name: "Chennai",
			displayName: "Chennai",
			aliases: ["chennai"],
			heroImage: "Chennai.jpg",

			description: {
				title: "Chennai's Premier Hubs for",
				highlight: "Growth",
				text: "Chennai, the cultural and economic capital of South India, is a thriving hub for manufacturing, IT, and business services. Our strategically positioned coworking spaces across Chennai offer modern facilities and a vibrant community. From Guindy to OMR, we provide the perfect environment for your business to succeed in this dynamic city.",
			},
			mapCenter: { lat: 13.0827, lng: 80.2707 },
			centers: [
				{
					id: "kochar-jade",
					centerKey: "kochar jade",
					name: "Kochar Jade",
					explore: "/centre/kochar-jade",
					description: "",
					address:
						"5th Floor, Kochar Jade, Ambedkar Nagar, SIDCO Industrial Estate, Guindy, Chennai, Tamil Nadu 600032",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 13.012861, lng: 80.202167 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/SF3ZQ6iWyPVh7TJr8",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/kochar_Building1.jpg",
						lobby: "../../assets/city/kochar_Lobby2.jpg",
						workspace: "../../assets/city/kochar_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "saravana-matrix",
					centerKey: "saravana matrix tower",
					name: "Saravana Matrix Tower",
					explore: "/centre/saravana-matrix",
					description: "",
					address:
						"SM Towers, 5th & 6th Floors of Saravana Matrix Tower, No.2 / 88, Seevaram Village. OMR. Perungudi, Chennai 600096",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 12.953833, lng: 80.241889 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/wrukPr5ays6NqNFt7",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/sm_Building1.jpg",
						lobby: "../../assets/city/sm_Lobby2.jpg",
						workspace: "../../assets/city/sm_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "sigapi-achi",
					centerKey: "sigapi achi",
					name: "Sigapi Achi",
					explore: "/centre/sigapi-achi",
					description: "",
					address:
						"No.18/3, Rukmani Lakshmipathi Road, Egmore, Chennai 600008",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 13.065833, lng: 80.259583 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/RopYTmVqgLzHUjMo8",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/sigapi_Building1.jpg",
						lobby: "../../assets/city/sigapi_Meeting Room2.jpg",
						workspace: "../../assets/city/sigapi_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "pune",
			name: "Pune",
			displayName: "Pune",
			aliases: ["pune"],
			heroImage: "Pune.jpg",
			description: {
				title: "Pune's Dynamic Spaces for",
				highlight: "Entrepreneurs",
				text: "Pune, known as the Oxford of the East, has emerged as a major IT and manufacturing hub in India. Our premium coworking spaces across Hinjawadi, Baner, and Yerawada provide the perfect blend of modern infrastructure and collaborative environment. Experience flexible workspaces designed for startups, SMEs, and enterprise teams in one of India's most liveable cities.",
			},
			mapCenter: { lat: 18.5204, lng: 73.8567 },
			centers: [
				{
					id: "greystone-baner",
					centerKey: "greystone baner",
					name: "Greystone Baner",
					explore: "/centre/greystone-baner",
					description: "",
					address:
						"iSprout GreyStone Tremont HQ7F+WFP, Near Kargar Facility Management Services, Veerbhadra Nagar, Baner, Pune, Maharashtra 411045",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 18.564917, lng: 73.773861 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/M4PfTuwwZdzE6N3x5",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/grey_Building1.jpg",
						lobby: "../../assets/city/grey_Lobby2.jpg",
						workspace: "../../assets/city/grey_Workspace13.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "panchshil-techpark",
					centerKey: "panchshil techpark",
					name: "Panchshil Techpark",
					explore: "/centre/panchshil-techpark",
					description: "",
					address:
						"4th Floor, Survey No 19, 20, Hinjawadi Village, Hinjawadi, Pune, Pimpri-Chinchwad, Maharashtra 411057",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 18.592673, lng: 73.746958 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/LF3PrJw9UEtuYttL6",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/panchasil_Building1.jpg",
						lobby: "../../assets/city/panchasil_Lobby2.jpg",
						workspace: "../../assets/city/panchasil_Workspace3.jpg",
					},
					contactUsPageImage: "",
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "panchshil-techpark-one",
					centerKey: "panchshil techpark one",
					name: "Panchshil Techpark One",
					explore: "/centre/panchshil-techpark-one",
					description: "",
					address:
						"Tower E, 191 IBM TECH PARK, Shastrinagar, Yerawada, Pune, Maharashtra 411006",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 18.552778, lng: 73.892546 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/DRQjZigBhhfDcHps9",
					heroImage: "",
					cityLevelImages: {
						building:
							"../../assets/city/panchasilone_Building1.jpg",
						lobby: "../../assets/city/panchasilone_Lobby2.jpg",
						workspace:
							"../../assets/city/panchasilone_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "vijayawada",
			name: "Vijayawada",
			displayName: "Vijayawada",
			aliases: ["vijayawada"],
			heroImage: "Vijayawada.jpg",

			description: {
				title: "Vijayawada's Prime Locations for",
				highlight: "Success",
				text: "Vijayawada, the business capital of Andhra Pradesh, is rapidly emerging as a key commercial and IT hub in South India. Our modern coworking spaces at Benz Circle and IT Park Road offer state-of-the-art facilities and a professional environment. Join a growing community of businesses and entrepreneurs in this strategic location connecting major cities of South India.",
			},
			mapCenter: { lat: 16.5062, lng: 80.648 },
			centers: [
				{
					id: "benz-circle",
					centerKey: "benz circle - amaravathi",
					name: "Benz Circle - Amaravathi",
					explore: "/centre/benz-circle",
					description: "",
					address:
						"Door No: 40-14-8/2, near jyothi convention hall, Benz Circle, Vijayawada, Andhra Pradesh 520010",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 16.497139, lng: 80.651528 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/wc7dEiyCqtVgph6SA",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/benz_Building1.jpg",
						lobby: "../../assets/city/benz_Lobby2.jpg",
						workspace: "../../assets/city/benz_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
				{
					id: "medha-towers",
					centerKey: "medha towers",
					name: "Medha Towers",
					explore: "/centre/medha-towers",
					description: "",
					address:
						"Sy. No. 53, Kesarapalli, IT Park Rd, Gannavaram, Vijayawada, Andhra Pradesh 521102",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 16.526056, lng: 80.779694 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/kAimhm46jLwsrWmx6",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/medha_Building1.jpg",
						lobby: "../../assets/city/medha_Lobby2.jpg",
						workspace: "../../assets/city/medha_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "kolkata",
			name: "Kolkata",
			displayName: "Kolkata",
			aliases: ["kolkata"],
			heroImage: "Kolkata.jpg",

			description: {
				title: "Kolkata's Modern Workspace for",
				highlight: "Visionaries",
				text: "Kolkata, the cultural capital of India, is witnessing a surge in startups and IT companies. Our premium coworking space in Sector V, Salt Lake provides world-class infrastructure and a collaborative ecosystem. Experience the perfect blend of tradition and innovation in the heart of Eastern India's IT corridor, where your business can thrive alongside industry leaders.",
			},
			mapCenter: { lat: 22.5726, lng: 88.3639 },
			centers: [
				{
					id: "godrej-waterside",
					centerKey: "godrej waterside",
					name: "Godrej Waterside",
					explore: "/centre/godrej-waterside",
					description: "",
					address:
						"Street No. 13, DP Block, Sector V, Bidhannagar, Kolkata, West Bengal 700091",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 22.573785, lng: 88.437549 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/kCmwCcqd78mzR6K68",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/godrej_Building1.jpg",
						lobby: "../../assets/city/godrej_Lobby2.jpg",
						workspace: "../../assets/city/godrej_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "ahmedabad",
			name: "Ahmedabad",
			displayName: "Ahmedabad",
			aliases: ["ahmedabad"],
			heroImage: "Amhedabad.jpg",

			description: {
				title: "Ahmedabad's Strategic Space for",
				highlight: "Achievers",
				text: "Ahmedabad, Gujarat's commercial hub, is a vibrant ecosystem for manufacturing, textiles, and emerging technology sectors. Our modern coworking space in Makarba offers premium facilities and a collaborative environment for businesses of all sizes. Be part of one of India's fastest-growing cities where tradition meets innovation and entrepreneurship thrives.",
			},
			mapCenter: { lat: 23.0225, lng: 72.5714 },
			centers: [
				{
					id: "aurelien",
					centerKey: "aurelien",
					name: "Aurelien",
					explore: "/centre/aurelien",
					description: "",
					address:
						"XFRQ+R4P, Makarba, Ahmedabad, Sarkhej-Okaf, Gujarat 380054",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 22.991388, lng: 72.487518 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/v8sXHeGUxhfSfA2n9",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/aurelien_Building1.jpg",
						lobby: "../../assets/city/aurelien_Lobby2.jpg",
						workspace: "../../assets/city/aurelien_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "gurugram",
			name: "Gurugram",
			displayName: "Delhi NCR",
			aliases: ["gurugram", "delhi-ncr", "delhi"],
			heroImage: "Delhi NCR.jpg",

			description: {
				title: "Gurugram's Premium Workspace for",
				highlight: "Leaders",
				text: "Gurugram, part of the National Capital Region, is India's leading corporate and financial hub. Our coworking space in Sushant Lok provides sophisticated infrastructure and a professional atmosphere in the heart of the city's business district. Join Fortune 500 companies and dynamic startups in this thriving metropolitan center that drives India's economic growth.",
			},
			mapCenter: { lat: 28.4595, lng: 77.0266 },
			centers: [
				{
					id: "hq27",
					centerKey: "hq27 the headquarters",
					name: "HQ27 The Headquarters",
					explore: "/centre/hq27",
					description: "",
					address:
						"B-660, 5th floor, Sushant Lok Phase I, Sector 27, Gurugram, Haryana 122009",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 28.466216, lng: 77.074073 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/5XKGfBbupH6DgWpV9",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/HQ27_Building1.jpg",
						lobby: "../../assets/city/HQ27_Lobby2.jpg",
						workspace: "../../assets/city/HQ27_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
		{
			id: "vizag",
			name: "Vizag",
			displayName: "Vizag",
			aliases: ["vizag"],
			heroImage: "Vizag.jpg",

			description: {
				title: "Vizag's Coastal Workspace for",
				highlight: "Innovators",
				text: "Visakhapatnam, fondly known as Vizag, is a major port city and industrial hub on India's eastern coast. Our premium coworking space at Lansum Square offers modern facilities and a professional environment for businesses looking to establish a presence in this strategic location. Experience the perfect blend of coastal charm and business opportunity in one of Andhra Pradesh's most dynamic cities.",
			},
			mapCenter: { lat: 17.7437, lng: 83.3273 },
			centers: [
				{
					id: "lansum-square",
					centerKey: "lansum square",
					name: "Lansum Square",
					explore: "/centre/lansum-square",
					description: "",
					address: "Lansum Square, Visakhapatnam, Andhra Pradesh",
					phone: "(+91) 8464999920",
					email: "marketing@isprout.in",
					coordinates: { lat: 17.743399, lng: 83.327411 },
					nearestCoordinates: [],
					getDirections: "https://maps.app.goo.gl/A9eYERsiV6XLksQNA",
					heroImage: "",
					cityLevelImages: {
						building: "../../assets/city/vizag_Building1.jpg",
						lobby: "../../assets/city/vizag_Lobby2.jpg",
						workspace: "../../assets/city/vizag_Workspace3.jpg",
					},
					centerLevelImages: [],
					videoLink: "",
				},
			],
		},
	],
};

// Helper function to get city data by name
export const getCityData = (cityName: string | undefined) => {
	const city = cityPageData.cities.find(
		(c) =>
			c.id === cityName?.toLowerCase() ||
			c.aliases.includes(cityName?.toLowerCase() || ""),
	);
	return city || cityPageData.cities[0];
};

// Helper function to get all city names
export const getAllCityNames = () => {
	return cityPageData.cities.map((city) => ({
		id: city.id,
		name: city.name,
		displayName: city.displayName,
	}));
};

// Helper function to get center data within a city
export const getCenterData = (
	cityName: string | undefined,
	centerName: string,
) => {
	const city = getCityData(cityName);
	return city.centers.find(
		(center) => center.centerKey === centerName.toLowerCase(),
	);
};

// Summary stats
export const cityStats = {
	totalCities: cityPageData.cities.length,
	totalCenters: cityPageData.cities.reduce(
		(sum, city) => sum + city.centers.length,
		0,
	),
	citiesWithCenters: cityPageData.cities.map((city) => ({
		city: city.name,
		centerCount: city.centers.length,
		centers: city.centers.map((c) => c.name),
	})),
};
